name: Rebase open PRs

on: workflow_dispatch

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
        name: Checkout repository
        id: checkout

      # Fetch the latest changes
      - run: git fetch
        name: Fetch latest changes

      # Get the list of open PRs
      - run: |
          open_prs=$(curl -s -H "Authorization: Bearer ${GITHUB_TOKEN}" https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls\?state\=open\&base\=develop | jq -r '.[].number')

          # Rebasing PRs
          for pr in $open_prs; do
            # Check if the PR has the "auto-rebase" label
            labels=$(curl -s -H "Authorization: Bearer ${GITHUB_TOKEN}" https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${pr}/labels)
            if echo "$labels" | grep -q "auto-rebase"; then
              echo "Rebasing PR #$pr (has the 'auto-rebase' label)"
              git checkout -b pr-$pr refs/pull/$pr/head
              git rebase develop
              git push -f --force-with-lease
              git checkout develop
              git branch -D pr-$pr
              echo "Successfully rebased and pushed PR #$pr"
            else
              echo "Skipping PR #$pr (does not have the 'auto-rebase' label)"
            fi
          done
